// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, RequestResult, TDataShape } from '../../shared/client';
import { client } from '../../shared/client.gen';
import type {
  CreateComputeDatumapisComV1AlphaNamespacedInstanceData,
  CreateComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  CreateComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadData,
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData,
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedInstanceData,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedInstanceErrors,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedInstanceResponses,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadData,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadDeploymentData,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadDeploymentErrors,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadDeploymentResponses,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadErrors,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadResponses,
  DeleteComputeDatumapisComV1AlphaNamespacedInstanceData,
  DeleteComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  DeleteComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadData,
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData,
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  ListComputeDatumapisComV1AlphaInstanceForAllNamespacesData,
  ListComputeDatumapisComV1AlphaInstanceForAllNamespacesErrors,
  ListComputeDatumapisComV1AlphaInstanceForAllNamespacesResponses,
  ListComputeDatumapisComV1AlphaNamespacedInstanceData,
  ListComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  ListComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  ListComputeDatumapisComV1AlphaNamespacedWorkloadData,
  ListComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData,
  ListComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  ListComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  ListComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  ListComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  ListComputeDatumapisComV1AlphaWorkloadDeploymentForAllNamespacesData,
  ListComputeDatumapisComV1AlphaWorkloadDeploymentForAllNamespacesErrors,
  ListComputeDatumapisComV1AlphaWorkloadDeploymentForAllNamespacesResponses,
  ListComputeDatumapisComV1AlphaWorkloadForAllNamespacesData,
  ListComputeDatumapisComV1AlphaWorkloadForAllNamespacesErrors,
  ListComputeDatumapisComV1AlphaWorkloadForAllNamespacesResponses,
  PatchComputeDatumapisComV1AlphaNamespacedInstanceData,
  PatchComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  PatchComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  PatchComputeDatumapisComV1AlphaNamespacedInstanceStatusData,
  PatchComputeDatumapisComV1AlphaNamespacedInstanceStatusErrors,
  PatchComputeDatumapisComV1AlphaNamespacedInstanceStatusResponses,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadData,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusData,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusErrors,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusResponses,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadStatusData,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadStatusErrors,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadStatusResponses,
  ReadComputeDatumapisComV1AlphaNamespacedInstanceData,
  ReadComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  ReadComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  ReadComputeDatumapisComV1AlphaNamespacedInstanceStatusData,
  ReadComputeDatumapisComV1AlphaNamespacedInstanceStatusErrors,
  ReadComputeDatumapisComV1AlphaNamespacedInstanceStatusResponses,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadData,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusData,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusErrors,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusResponses,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadStatusData,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadStatusErrors,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadStatusResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceData,
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceStatusData,
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceStatusErrors,
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceStatusResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadData,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusData,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusErrors,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadStatusData,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadStatusErrors,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * list objects of kind Instance
 */
export const listComputeDatumapisComV1AlphaInstanceForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListComputeDatumapisComV1AlphaInstanceForAllNamespacesData, ThrowOnError>
): RequestResult<
  ListComputeDatumapisComV1AlphaInstanceForAllNamespacesResponses,
  ListComputeDatumapisComV1AlphaInstanceForAllNamespacesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListComputeDatumapisComV1AlphaInstanceForAllNamespacesResponses,
    ListComputeDatumapisComV1AlphaInstanceForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/instances',
    ...options,
  });

/**
 * delete collection of Instance
 */
export const deleteComputeDatumapisComV1AlphaCollectionNamespacedInstance = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteComputeDatumapisComV1AlphaCollectionNamespacedInstanceData, ThrowOnError>
): RequestResult<
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedInstanceResponses,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedInstanceErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteComputeDatumapisComV1AlphaCollectionNamespacedInstanceResponses,
    DeleteComputeDatumapisComV1AlphaCollectionNamespacedInstanceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances',
    ...options,
  });

/**
 * list objects of kind Instance
 */
export const listComputeDatumapisComV1AlphaNamespacedInstance = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ListComputeDatumapisComV1AlphaNamespacedInstanceData, ThrowOnError>
): RequestResult<
  ListComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  ListComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListComputeDatumapisComV1AlphaNamespacedInstanceResponses,
    ListComputeDatumapisComV1AlphaNamespacedInstanceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances',
    ...options,
  });

/**
 * create an Instance
 */
export const createComputeDatumapisComV1AlphaNamespacedInstance = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateComputeDatumapisComV1AlphaNamespacedInstanceData, ThrowOnError>
): RequestResult<
  CreateComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  CreateComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateComputeDatumapisComV1AlphaNamespacedInstanceResponses,
    CreateComputeDatumapisComV1AlphaNamespacedInstanceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete an Instance
 */
export const deleteComputeDatumapisComV1AlphaNamespacedInstance = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteComputeDatumapisComV1AlphaNamespacedInstanceData, ThrowOnError>
): RequestResult<
  DeleteComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  DeleteComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteComputeDatumapisComV1AlphaNamespacedInstanceResponses,
    DeleteComputeDatumapisComV1AlphaNamespacedInstanceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Instance
 */
export const readComputeDatumapisComV1AlphaNamespacedInstance = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadComputeDatumapisComV1AlphaNamespacedInstanceData, ThrowOnError>
): RequestResult<
  ReadComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  ReadComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadComputeDatumapisComV1AlphaNamespacedInstanceResponses,
    ReadComputeDatumapisComV1AlphaNamespacedInstanceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances/{name}',
    ...options,
  });

/**
 * partially update the specified Instance
 */
export const patchComputeDatumapisComV1AlphaNamespacedInstance = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchComputeDatumapisComV1AlphaNamespacedInstanceData, ThrowOnError>
): RequestResult<
  PatchComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  PatchComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchComputeDatumapisComV1AlphaNamespacedInstanceResponses,
    PatchComputeDatumapisComV1AlphaNamespacedInstanceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Instance
 */
export const replaceComputeDatumapisComV1AlphaNamespacedInstance = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceComputeDatumapisComV1AlphaNamespacedInstanceData, ThrowOnError>
): RequestResult<
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceComputeDatumapisComV1AlphaNamespacedInstanceResponses,
    ReplaceComputeDatumapisComV1AlphaNamespacedInstanceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Instance
 */
export const readComputeDatumapisComV1AlphaNamespacedInstanceStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadComputeDatumapisComV1AlphaNamespacedInstanceStatusData, ThrowOnError>
): RequestResult<
  ReadComputeDatumapisComV1AlphaNamespacedInstanceStatusResponses,
  ReadComputeDatumapisComV1AlphaNamespacedInstanceStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadComputeDatumapisComV1AlphaNamespacedInstanceStatusResponses,
    ReadComputeDatumapisComV1AlphaNamespacedInstanceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Instance
 */
export const patchComputeDatumapisComV1AlphaNamespacedInstanceStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchComputeDatumapisComV1AlphaNamespacedInstanceStatusData, ThrowOnError>
): RequestResult<
  PatchComputeDatumapisComV1AlphaNamespacedInstanceStatusResponses,
  PatchComputeDatumapisComV1AlphaNamespacedInstanceStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchComputeDatumapisComV1AlphaNamespacedInstanceStatusResponses,
    PatchComputeDatumapisComV1AlphaNamespacedInstanceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Instance
 */
export const replaceComputeDatumapisComV1AlphaNamespacedInstanceStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceComputeDatumapisComV1AlphaNamespacedInstanceStatusData, ThrowOnError>
): RequestResult<
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceStatusResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedInstanceStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceComputeDatumapisComV1AlphaNamespacedInstanceStatusResponses,
    ReplaceComputeDatumapisComV1AlphaNamespacedInstanceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/instances/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of WorkloadDeployment
 */
export const deleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadDeployment = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadDeploymentData,
    ThrowOnError
  >
): RequestResult<
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadDeploymentResponses,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadDeploymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadDeploymentResponses,
    DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadDeploymentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments',
    ...options,
  });

/**
 * list objects of kind WorkloadDeployment
 */
export const listComputeDatumapisComV1AlphaNamespacedWorkloadDeployment = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ListComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData, ThrowOnError>
): RequestResult<
  ListComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  ListComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
    ListComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments',
    ...options,
  });

/**
 * create a WorkloadDeployment
 */
export const createComputeDatumapisComV1AlphaNamespacedWorkloadDeployment = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData, ThrowOnError>
): RequestResult<
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
    CreateComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a WorkloadDeployment
 */
export const deleteComputeDatumapisComV1AlphaNamespacedWorkloadDeployment = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData, ThrowOnError>
): RequestResult<
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
    DeleteComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified WorkloadDeployment
 */
export const readComputeDatumapisComV1AlphaNamespacedWorkloadDeployment = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData, ThrowOnError>
): RequestResult<
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
    ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments/{name}',
    ...options,
  });

/**
 * partially update the specified WorkloadDeployment
 */
export const patchComputeDatumapisComV1AlphaNamespacedWorkloadDeployment = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData, ThrowOnError>
): RequestResult<
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
    PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified WorkloadDeployment
 */
export const replaceComputeDatumapisComV1AlphaNamespacedWorkloadDeployment = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentData, ThrowOnError>
): RequestResult<
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentResponses,
    ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified WorkloadDeployment
 */
export const readComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusData,
    ThrowOnError
  >
): RequestResult<
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusResponses,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusResponses,
    ReadComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified WorkloadDeployment
 */
export const patchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusData,
    ThrowOnError
  >
): RequestResult<
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusResponses,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusResponses,
    PatchComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified WorkloadDeployment
 */
export const replaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusData,
    ThrowOnError
  >
): RequestResult<
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusResponses,
    ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadDeploymentStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloaddeployments/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Workload
 */
export const deleteComputeDatumapisComV1AlphaCollectionNamespacedWorkload = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadData, ThrowOnError>
): RequestResult<
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadResponses,
  DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadResponses,
    DeleteComputeDatumapisComV1AlphaCollectionNamespacedWorkloadErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads',
    ...options,
  });

/**
 * list objects of kind Workload
 */
export const listComputeDatumapisComV1AlphaNamespacedWorkload = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ListComputeDatumapisComV1AlphaNamespacedWorkloadData, ThrowOnError>
): RequestResult<
  ListComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  ListComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
    ListComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads',
    ...options,
  });

/**
 * create a Workload
 */
export const createComputeDatumapisComV1AlphaNamespacedWorkload = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateComputeDatumapisComV1AlphaNamespacedWorkloadData, ThrowOnError>
): RequestResult<
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  CreateComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
    CreateComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Workload
 */
export const deleteComputeDatumapisComV1AlphaNamespacedWorkload = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteComputeDatumapisComV1AlphaNamespacedWorkloadData, ThrowOnError>
): RequestResult<
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  DeleteComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
    DeleteComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Workload
 */
export const readComputeDatumapisComV1AlphaNamespacedWorkload = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadComputeDatumapisComV1AlphaNamespacedWorkloadData, ThrowOnError>
): RequestResult<
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
    ReadComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads/{name}',
    ...options,
  });

/**
 * partially update the specified Workload
 */
export const patchComputeDatumapisComV1AlphaNamespacedWorkload = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchComputeDatumapisComV1AlphaNamespacedWorkloadData, ThrowOnError>
): RequestResult<
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
    PatchComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Workload
 */
export const replaceComputeDatumapisComV1AlphaNamespacedWorkload = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadData, ThrowOnError>
): RequestResult<
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadResponses,
    ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Workload
 */
export const readComputeDatumapisComV1AlphaNamespacedWorkloadStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadComputeDatumapisComV1AlphaNamespacedWorkloadStatusData, ThrowOnError>
): RequestResult<
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadStatusResponses,
  ReadComputeDatumapisComV1AlphaNamespacedWorkloadStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadComputeDatumapisComV1AlphaNamespacedWorkloadStatusResponses,
    ReadComputeDatumapisComV1AlphaNamespacedWorkloadStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Workload
 */
export const patchComputeDatumapisComV1AlphaNamespacedWorkloadStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchComputeDatumapisComV1AlphaNamespacedWorkloadStatusData, ThrowOnError>
): RequestResult<
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadStatusResponses,
  PatchComputeDatumapisComV1AlphaNamespacedWorkloadStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchComputeDatumapisComV1AlphaNamespacedWorkloadStatusResponses,
    PatchComputeDatumapisComV1AlphaNamespacedWorkloadStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Workload
 */
export const replaceComputeDatumapisComV1AlphaNamespacedWorkloadStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadStatusData, ThrowOnError>
): RequestResult<
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadStatusResponses,
  ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadStatusResponses,
    ReplaceComputeDatumapisComV1AlphaNamespacedWorkloadStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/namespaces/{namespace}/workloads/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * list objects of kind WorkloadDeployment
 */
export const listComputeDatumapisComV1AlphaWorkloadDeploymentForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    ListComputeDatumapisComV1AlphaWorkloadDeploymentForAllNamespacesData,
    ThrowOnError
  >
): RequestResult<
  ListComputeDatumapisComV1AlphaWorkloadDeploymentForAllNamespacesResponses,
  ListComputeDatumapisComV1AlphaWorkloadDeploymentForAllNamespacesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListComputeDatumapisComV1AlphaWorkloadDeploymentForAllNamespacesResponses,
    ListComputeDatumapisComV1AlphaWorkloadDeploymentForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/workloaddeployments',
    ...options,
  });

/**
 * list objects of kind Workload
 */
export const listComputeDatumapisComV1AlphaWorkloadForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListComputeDatumapisComV1AlphaWorkloadForAllNamespacesData, ThrowOnError>
): RequestResult<
  ListComputeDatumapisComV1AlphaWorkloadForAllNamespacesResponses,
  ListComputeDatumapisComV1AlphaWorkloadForAllNamespacesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListComputeDatumapisComV1AlphaWorkloadForAllNamespacesResponses,
    ListComputeDatumapisComV1AlphaWorkloadForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compute.datumapis.com/v1alpha/workloads',
    ...options,
  });
