// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, RequestResult, TDataShape } from '../../shared/client';
import { client } from '../../shared/client.gen';
import type {
  CreateStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
  CreateStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  CreateStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  CreateStripeBillingMiloapisComV1Alpha1StripeProviderConfigData,
  CreateStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  CreateStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  DeleteStripeBillingMiloapisComV1Alpha1CollectionNamespacedStripePaymentMethodData,
  DeleteStripeBillingMiloapisComV1Alpha1CollectionNamespacedStripePaymentMethodErrors,
  DeleteStripeBillingMiloapisComV1Alpha1CollectionNamespacedStripePaymentMethodResponses,
  DeleteStripeBillingMiloapisComV1Alpha1CollectionStripeProviderConfigData,
  DeleteStripeBillingMiloapisComV1Alpha1CollectionStripeProviderConfigErrors,
  DeleteStripeBillingMiloapisComV1Alpha1CollectionStripeProviderConfigResponses,
  DeleteStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
  DeleteStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  DeleteStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  DeleteStripeBillingMiloapisComV1Alpha1StripeProviderConfigData,
  DeleteStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  DeleteStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  ListStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
  ListStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  ListStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  ListStripeBillingMiloapisComV1Alpha1StripePaymentMethodForAllNamespacesData,
  ListStripeBillingMiloapisComV1Alpha1StripePaymentMethodForAllNamespacesErrors,
  ListStripeBillingMiloapisComV1Alpha1StripePaymentMethodForAllNamespacesResponses,
  ListStripeBillingMiloapisComV1Alpha1StripeProviderConfigData,
  ListStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  ListStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusData,
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusErrors,
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusResponses,
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigData,
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusData,
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusErrors,
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusResponses,
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusData,
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusErrors,
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusResponses,
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigData,
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusData,
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusErrors,
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusResponses,
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusData,
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusErrors,
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusResponses,
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigData,
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusData,
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusErrors,
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * delete collection of StripePaymentMethod
 */
export const deleteStripeBillingMiloapisComV1Alpha1CollectionNamespacedStripePaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteStripeBillingMiloapisComV1Alpha1CollectionNamespacedStripePaymentMethodData,
    ThrowOnError
  >
): RequestResult<
  DeleteStripeBillingMiloapisComV1Alpha1CollectionNamespacedStripePaymentMethodResponses,
  DeleteStripeBillingMiloapisComV1Alpha1CollectionNamespacedStripePaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteStripeBillingMiloapisComV1Alpha1CollectionNamespacedStripePaymentMethodResponses,
    DeleteStripeBillingMiloapisComV1Alpha1CollectionNamespacedStripePaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods',
    ...options,
  });

/**
 * list objects of kind StripePaymentMethod
 */
export const listStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ListStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
    ThrowOnError
  >
): RequestResult<
  ListStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  ListStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
    ListStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods',
    ...options,
  });

/**
 * create a StripePaymentMethod
 */
export const createStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    CreateStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
    ThrowOnError
  >
): RequestResult<
  CreateStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  CreateStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
    CreateStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a StripePaymentMethod
 */
export const deleteStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
    ThrowOnError
  >
): RequestResult<
  DeleteStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  DeleteStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
    DeleteStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified StripePaymentMethod
 */
export const readStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
    ThrowOnError
  >
): RequestResult<
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
    ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods/{name}',
    ...options,
  });

/**
 * partially update the specified StripePaymentMethod
 */
export const patchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
    ThrowOnError
  >
): RequestResult<
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
    PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified StripePaymentMethod
 */
export const replaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodData,
    ThrowOnError
  >
): RequestResult<
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodResponses,
    ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified StripePaymentMethod
 */
export const readStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusData,
    ThrowOnError
  >
): RequestResult<
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusResponses,
  ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusResponses,
    ReadStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified StripePaymentMethod
 */
export const patchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusData,
    ThrowOnError
  >
): RequestResult<
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusResponses,
  PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusResponses,
    PatchStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified StripePaymentMethod
 */
export const replaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusData,
    ThrowOnError
  >
): RequestResult<
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusResponses,
  ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusResponses,
    ReplaceStripeBillingMiloapisComV1Alpha1NamespacedStripePaymentMethodStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/namespaces/{namespace}/stripepaymentmethods/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * list objects of kind StripePaymentMethod
 */
export const listStripeBillingMiloapisComV1Alpha1StripePaymentMethodForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    ListStripeBillingMiloapisComV1Alpha1StripePaymentMethodForAllNamespacesData,
    ThrowOnError
  >
): RequestResult<
  ListStripeBillingMiloapisComV1Alpha1StripePaymentMethodForAllNamespacesResponses,
  ListStripeBillingMiloapisComV1Alpha1StripePaymentMethodForAllNamespacesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListStripeBillingMiloapisComV1Alpha1StripePaymentMethodForAllNamespacesResponses,
    ListStripeBillingMiloapisComV1Alpha1StripePaymentMethodForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripepaymentmethods',
    ...options,
  });

/**
 * delete collection of StripeProviderConfig
 */
export const deleteStripeBillingMiloapisComV1Alpha1CollectionStripeProviderConfig = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    DeleteStripeBillingMiloapisComV1Alpha1CollectionStripeProviderConfigData,
    ThrowOnError
  >
): RequestResult<
  DeleteStripeBillingMiloapisComV1Alpha1CollectionStripeProviderConfigResponses,
  DeleteStripeBillingMiloapisComV1Alpha1CollectionStripeProviderConfigErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    DeleteStripeBillingMiloapisComV1Alpha1CollectionStripeProviderConfigResponses,
    DeleteStripeBillingMiloapisComV1Alpha1CollectionStripeProviderConfigErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs',
    ...options,
  });

/**
 * list objects of kind StripeProviderConfig
 */
export const listStripeBillingMiloapisComV1Alpha1StripeProviderConfig = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListStripeBillingMiloapisComV1Alpha1StripeProviderConfigData, ThrowOnError>
): RequestResult<
  ListStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  ListStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
    ListStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs',
    ...options,
  });

/**
 * create a StripeProviderConfig
 */
export const createStripeBillingMiloapisComV1Alpha1StripeProviderConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateStripeBillingMiloapisComV1Alpha1StripeProviderConfigData, ThrowOnError>
): RequestResult<
  CreateStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  CreateStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
    CreateStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a StripeProviderConfig
 */
export const deleteStripeBillingMiloapisComV1Alpha1StripeProviderConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteStripeBillingMiloapisComV1Alpha1StripeProviderConfigData, ThrowOnError>
): RequestResult<
  DeleteStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  DeleteStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
    DeleteStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified StripeProviderConfig
 */
export const readStripeBillingMiloapisComV1Alpha1StripeProviderConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigData, ThrowOnError>
): RequestResult<
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
    ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs/{name}',
    ...options,
  });

/**
 * partially update the specified StripeProviderConfig
 */
export const patchStripeBillingMiloapisComV1Alpha1StripeProviderConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigData, ThrowOnError>
): RequestResult<
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
    PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified StripeProviderConfig
 */
export const replaceStripeBillingMiloapisComV1Alpha1StripeProviderConfig = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigData, ThrowOnError>
): RequestResult<
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigResponses,
    ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified StripeProviderConfig
 */
export const readStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusData, ThrowOnError>
): RequestResult<
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusResponses,
  ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusResponses,
    ReadStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified StripeProviderConfig
 */
export const patchStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusData,
    ThrowOnError
  >
): RequestResult<
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusResponses,
  PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusResponses,
    PatchStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified StripeProviderConfig
 */
export const replaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusData,
    ThrowOnError
  >
): RequestResult<
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusResponses,
  ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusResponses,
    ReplaceStripeBillingMiloapisComV1Alpha1StripeProviderConfigStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/stripe.billing.miloapis.com/v1alpha1/stripeproviderconfigs/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
