// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../../shared/client';
import { client } from '../../shared/client.gen';
import type {
  CreateComplianceMiloapisComV1Alpha1SubprocessorData,
  CreateComplianceMiloapisComV1Alpha1SubprocessorErrors,
  CreateComplianceMiloapisComV1Alpha1SubprocessorResponses,
  CreateComplianceMiloapisComV1Alpha1VendorData,
  CreateComplianceMiloapisComV1Alpha1VendorErrors,
  CreateComplianceMiloapisComV1Alpha1VendorResponses,
  DeleteComplianceMiloapisComV1Alpha1CollectionSubprocessorData,
  DeleteComplianceMiloapisComV1Alpha1CollectionSubprocessorErrors,
  DeleteComplianceMiloapisComV1Alpha1CollectionSubprocessorResponses,
  DeleteComplianceMiloapisComV1Alpha1CollectionVendorData,
  DeleteComplianceMiloapisComV1Alpha1CollectionVendorErrors,
  DeleteComplianceMiloapisComV1Alpha1CollectionVendorResponses,
  DeleteComplianceMiloapisComV1Alpha1SubprocessorData,
  DeleteComplianceMiloapisComV1Alpha1SubprocessorErrors,
  DeleteComplianceMiloapisComV1Alpha1SubprocessorResponses,
  DeleteComplianceMiloapisComV1Alpha1VendorData,
  DeleteComplianceMiloapisComV1Alpha1VendorErrors,
  DeleteComplianceMiloapisComV1Alpha1VendorResponses,
  ListComplianceMiloapisComV1Alpha1SubprocessorData,
  ListComplianceMiloapisComV1Alpha1SubprocessorErrors,
  ListComplianceMiloapisComV1Alpha1SubprocessorResponses,
  ListComplianceMiloapisComV1Alpha1VendorData,
  ListComplianceMiloapisComV1Alpha1VendorErrors,
  ListComplianceMiloapisComV1Alpha1VendorResponses,
  PatchComplianceMiloapisComV1Alpha1SubprocessorData,
  PatchComplianceMiloapisComV1Alpha1SubprocessorErrors,
  PatchComplianceMiloapisComV1Alpha1SubprocessorResponses,
  PatchComplianceMiloapisComV1Alpha1SubprocessorStatusData,
  PatchComplianceMiloapisComV1Alpha1SubprocessorStatusErrors,
  PatchComplianceMiloapisComV1Alpha1SubprocessorStatusResponses,
  PatchComplianceMiloapisComV1Alpha1VendorData,
  PatchComplianceMiloapisComV1Alpha1VendorErrors,
  PatchComplianceMiloapisComV1Alpha1VendorResponses,
  PatchComplianceMiloapisComV1Alpha1VendorStatusData,
  PatchComplianceMiloapisComV1Alpha1VendorStatusErrors,
  PatchComplianceMiloapisComV1Alpha1VendorStatusResponses,
  ReadComplianceMiloapisComV1Alpha1SubprocessorData,
  ReadComplianceMiloapisComV1Alpha1SubprocessorErrors,
  ReadComplianceMiloapisComV1Alpha1SubprocessorResponses,
  ReadComplianceMiloapisComV1Alpha1SubprocessorStatusData,
  ReadComplianceMiloapisComV1Alpha1SubprocessorStatusErrors,
  ReadComplianceMiloapisComV1Alpha1SubprocessorStatusResponses,
  ReadComplianceMiloapisComV1Alpha1VendorData,
  ReadComplianceMiloapisComV1Alpha1VendorErrors,
  ReadComplianceMiloapisComV1Alpha1VendorResponses,
  ReadComplianceMiloapisComV1Alpha1VendorStatusData,
  ReadComplianceMiloapisComV1Alpha1VendorStatusErrors,
  ReadComplianceMiloapisComV1Alpha1VendorStatusResponses,
  ReplaceComplianceMiloapisComV1Alpha1SubprocessorData,
  ReplaceComplianceMiloapisComV1Alpha1SubprocessorErrors,
  ReplaceComplianceMiloapisComV1Alpha1SubprocessorResponses,
  ReplaceComplianceMiloapisComV1Alpha1SubprocessorStatusData,
  ReplaceComplianceMiloapisComV1Alpha1SubprocessorStatusErrors,
  ReplaceComplianceMiloapisComV1Alpha1SubprocessorStatusResponses,
  ReplaceComplianceMiloapisComV1Alpha1VendorData,
  ReplaceComplianceMiloapisComV1Alpha1VendorErrors,
  ReplaceComplianceMiloapisComV1Alpha1VendorResponses,
  ReplaceComplianceMiloapisComV1Alpha1VendorStatusData,
  ReplaceComplianceMiloapisComV1Alpha1VendorStatusErrors,
  ReplaceComplianceMiloapisComV1Alpha1VendorStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * delete collection of Subprocessor
 */
export const deleteComplianceMiloapisComV1Alpha1CollectionSubprocessor = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<DeleteComplianceMiloapisComV1Alpha1CollectionSubprocessorData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteComplianceMiloapisComV1Alpha1CollectionSubprocessorResponses,
    DeleteComplianceMiloapisComV1Alpha1CollectionSubprocessorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors',
    ...options,
  });

/**
 * list objects of kind Subprocessor
 */
export const listComplianceMiloapisComV1Alpha1Subprocessor = <ThrowOnError extends boolean = true>(
  options?: Options<ListComplianceMiloapisComV1Alpha1SubprocessorData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListComplianceMiloapisComV1Alpha1SubprocessorResponses,
    ListComplianceMiloapisComV1Alpha1SubprocessorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors',
    ...options,
  });

/**
 * create a Subprocessor
 */
export const createComplianceMiloapisComV1Alpha1Subprocessor = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateComplianceMiloapisComV1Alpha1SubprocessorData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateComplianceMiloapisComV1Alpha1SubprocessorResponses,
    CreateComplianceMiloapisComV1Alpha1SubprocessorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Subprocessor
 */
export const deleteComplianceMiloapisComV1Alpha1Subprocessor = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteComplianceMiloapisComV1Alpha1SubprocessorData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteComplianceMiloapisComV1Alpha1SubprocessorResponses,
    DeleteComplianceMiloapisComV1Alpha1SubprocessorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Subprocessor
 */
export const readComplianceMiloapisComV1Alpha1Subprocessor = <ThrowOnError extends boolean = true>(
  options: Options<ReadComplianceMiloapisComV1Alpha1SubprocessorData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadComplianceMiloapisComV1Alpha1SubprocessorResponses,
    ReadComplianceMiloapisComV1Alpha1SubprocessorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors/{name}',
    ...options,
  });

/**
 * partially update the specified Subprocessor
 */
export const patchComplianceMiloapisComV1Alpha1Subprocessor = <ThrowOnError extends boolean = true>(
  options: Options<PatchComplianceMiloapisComV1Alpha1SubprocessorData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchComplianceMiloapisComV1Alpha1SubprocessorResponses,
    PatchComplianceMiloapisComV1Alpha1SubprocessorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Subprocessor
 */
export const replaceComplianceMiloapisComV1Alpha1Subprocessor = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceComplianceMiloapisComV1Alpha1SubprocessorData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceComplianceMiloapisComV1Alpha1SubprocessorResponses,
    ReplaceComplianceMiloapisComV1Alpha1SubprocessorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Subprocessor
 */
export const readComplianceMiloapisComV1Alpha1SubprocessorStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadComplianceMiloapisComV1Alpha1SubprocessorStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadComplianceMiloapisComV1Alpha1SubprocessorStatusResponses,
    ReadComplianceMiloapisComV1Alpha1SubprocessorStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Subprocessor
 */
export const patchComplianceMiloapisComV1Alpha1SubprocessorStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchComplianceMiloapisComV1Alpha1SubprocessorStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchComplianceMiloapisComV1Alpha1SubprocessorStatusResponses,
    PatchComplianceMiloapisComV1Alpha1SubprocessorStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Subprocessor
 */
export const replaceComplianceMiloapisComV1Alpha1SubprocessorStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceComplianceMiloapisComV1Alpha1SubprocessorStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceComplianceMiloapisComV1Alpha1SubprocessorStatusResponses,
    ReplaceComplianceMiloapisComV1Alpha1SubprocessorStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/subprocessors/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Vendor
 */
export const deleteComplianceMiloapisComV1Alpha1CollectionVendor = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<DeleteComplianceMiloapisComV1Alpha1CollectionVendorData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteComplianceMiloapisComV1Alpha1CollectionVendorResponses,
    DeleteComplianceMiloapisComV1Alpha1CollectionVendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors',
    ...options,
  });

/**
 * list objects of kind Vendor
 */
export const listComplianceMiloapisComV1Alpha1Vendor = <ThrowOnError extends boolean = true>(
  options?: Options<ListComplianceMiloapisComV1Alpha1VendorData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListComplianceMiloapisComV1Alpha1VendorResponses,
    ListComplianceMiloapisComV1Alpha1VendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors',
    ...options,
  });

/**
 * create a Vendor
 */
export const createComplianceMiloapisComV1Alpha1Vendor = <ThrowOnError extends boolean = true>(
  options: Options<CreateComplianceMiloapisComV1Alpha1VendorData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateComplianceMiloapisComV1Alpha1VendorResponses,
    CreateComplianceMiloapisComV1Alpha1VendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Vendor
 */
export const deleteComplianceMiloapisComV1Alpha1Vendor = <ThrowOnError extends boolean = true>(
  options: Options<DeleteComplianceMiloapisComV1Alpha1VendorData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteComplianceMiloapisComV1Alpha1VendorResponses,
    DeleteComplianceMiloapisComV1Alpha1VendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Vendor
 */
export const readComplianceMiloapisComV1Alpha1Vendor = <ThrowOnError extends boolean = true>(
  options: Options<ReadComplianceMiloapisComV1Alpha1VendorData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadComplianceMiloapisComV1Alpha1VendorResponses,
    ReadComplianceMiloapisComV1Alpha1VendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors/{name}',
    ...options,
  });

/**
 * partially update the specified Vendor
 */
export const patchComplianceMiloapisComV1Alpha1Vendor = <ThrowOnError extends boolean = true>(
  options: Options<PatchComplianceMiloapisComV1Alpha1VendorData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchComplianceMiloapisComV1Alpha1VendorResponses,
    PatchComplianceMiloapisComV1Alpha1VendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Vendor
 */
export const replaceComplianceMiloapisComV1Alpha1Vendor = <ThrowOnError extends boolean = true>(
  options: Options<ReplaceComplianceMiloapisComV1Alpha1VendorData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceComplianceMiloapisComV1Alpha1VendorResponses,
    ReplaceComplianceMiloapisComV1Alpha1VendorErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Vendor
 */
export const readComplianceMiloapisComV1Alpha1VendorStatus = <ThrowOnError extends boolean = true>(
  options: Options<ReadComplianceMiloapisComV1Alpha1VendorStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadComplianceMiloapisComV1Alpha1VendorStatusResponses,
    ReadComplianceMiloapisComV1Alpha1VendorStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Vendor
 */
export const patchComplianceMiloapisComV1Alpha1VendorStatus = <ThrowOnError extends boolean = true>(
  options: Options<PatchComplianceMiloapisComV1Alpha1VendorStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchComplianceMiloapisComV1Alpha1VendorStatusResponses,
    PatchComplianceMiloapisComV1Alpha1VendorStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Vendor
 */
export const replaceComplianceMiloapisComV1Alpha1VendorStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceComplianceMiloapisComV1Alpha1VendorStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceComplianceMiloapisComV1Alpha1VendorStatusResponses,
    ReplaceComplianceMiloapisComV1Alpha1VendorStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/compliance.miloapis.com/v1alpha1/vendors/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
