// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../../shared/client';
import { client } from '../../shared/client.gen';
import type {
  CreateServicesMiloapisComV1Alpha1ServiceConfigurationData,
  CreateServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
  CreateServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
  CreateServicesMiloapisComV1Alpha1ServiceConsumerData,
  CreateServicesMiloapisComV1Alpha1ServiceConsumerErrors,
  CreateServicesMiloapisComV1Alpha1ServiceConsumerResponses,
  CreateServicesMiloapisComV1Alpha1ServiceData,
  CreateServicesMiloapisComV1Alpha1ServiceEntitlementData,
  CreateServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
  CreateServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
  CreateServicesMiloapisComV1Alpha1ServiceErrors,
  CreateServicesMiloapisComV1Alpha1ServiceResponses,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceConfigurationData,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceConfigurationErrors,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceConfigurationResponses,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceConsumerData,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceConsumerErrors,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceConsumerResponses,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceData,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceEntitlementData,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceEntitlementErrors,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceEntitlementResponses,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceErrors,
  DeleteServicesMiloapisComV1Alpha1CollectionServiceResponses,
  DeleteServicesMiloapisComV1Alpha1ServiceConfigurationData,
  DeleteServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
  DeleteServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
  DeleteServicesMiloapisComV1Alpha1ServiceConsumerData,
  DeleteServicesMiloapisComV1Alpha1ServiceConsumerErrors,
  DeleteServicesMiloapisComV1Alpha1ServiceConsumerResponses,
  DeleteServicesMiloapisComV1Alpha1ServiceData,
  DeleteServicesMiloapisComV1Alpha1ServiceEntitlementData,
  DeleteServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
  DeleteServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
  DeleteServicesMiloapisComV1Alpha1ServiceErrors,
  DeleteServicesMiloapisComV1Alpha1ServiceResponses,
  ListServicesMiloapisComV1Alpha1ServiceConfigurationData,
  ListServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
  ListServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
  ListServicesMiloapisComV1Alpha1ServiceConsumerData,
  ListServicesMiloapisComV1Alpha1ServiceConsumerErrors,
  ListServicesMiloapisComV1Alpha1ServiceConsumerResponses,
  ListServicesMiloapisComV1Alpha1ServiceData,
  ListServicesMiloapisComV1Alpha1ServiceEntitlementData,
  ListServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
  ListServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
  ListServicesMiloapisComV1Alpha1ServiceErrors,
  ListServicesMiloapisComV1Alpha1ServiceResponses,
  PatchServicesMiloapisComV1Alpha1ServiceConfigurationData,
  PatchServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
  PatchServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
  PatchServicesMiloapisComV1Alpha1ServiceConfigurationStatusData,
  PatchServicesMiloapisComV1Alpha1ServiceConfigurationStatusErrors,
  PatchServicesMiloapisComV1Alpha1ServiceConfigurationStatusResponses,
  PatchServicesMiloapisComV1Alpha1ServiceConsumerData,
  PatchServicesMiloapisComV1Alpha1ServiceConsumerErrors,
  PatchServicesMiloapisComV1Alpha1ServiceConsumerResponses,
  PatchServicesMiloapisComV1Alpha1ServiceConsumerStatusData,
  PatchServicesMiloapisComV1Alpha1ServiceConsumerStatusErrors,
  PatchServicesMiloapisComV1Alpha1ServiceConsumerStatusResponses,
  PatchServicesMiloapisComV1Alpha1ServiceData,
  PatchServicesMiloapisComV1Alpha1ServiceEntitlementData,
  PatchServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
  PatchServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
  PatchServicesMiloapisComV1Alpha1ServiceEntitlementStatusData,
  PatchServicesMiloapisComV1Alpha1ServiceEntitlementStatusErrors,
  PatchServicesMiloapisComV1Alpha1ServiceEntitlementStatusResponses,
  PatchServicesMiloapisComV1Alpha1ServiceErrors,
  PatchServicesMiloapisComV1Alpha1ServiceResponses,
  PatchServicesMiloapisComV1Alpha1ServiceStatusData,
  PatchServicesMiloapisComV1Alpha1ServiceStatusErrors,
  PatchServicesMiloapisComV1Alpha1ServiceStatusResponses,
  ReadServicesMiloapisComV1Alpha1ServiceConfigurationData,
  ReadServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
  ReadServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
  ReadServicesMiloapisComV1Alpha1ServiceConfigurationStatusData,
  ReadServicesMiloapisComV1Alpha1ServiceConfigurationStatusErrors,
  ReadServicesMiloapisComV1Alpha1ServiceConfigurationStatusResponses,
  ReadServicesMiloapisComV1Alpha1ServiceConsumerData,
  ReadServicesMiloapisComV1Alpha1ServiceConsumerErrors,
  ReadServicesMiloapisComV1Alpha1ServiceConsumerResponses,
  ReadServicesMiloapisComV1Alpha1ServiceConsumerStatusData,
  ReadServicesMiloapisComV1Alpha1ServiceConsumerStatusErrors,
  ReadServicesMiloapisComV1Alpha1ServiceConsumerStatusResponses,
  ReadServicesMiloapisComV1Alpha1ServiceData,
  ReadServicesMiloapisComV1Alpha1ServiceEntitlementData,
  ReadServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
  ReadServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
  ReadServicesMiloapisComV1Alpha1ServiceEntitlementStatusData,
  ReadServicesMiloapisComV1Alpha1ServiceEntitlementStatusErrors,
  ReadServicesMiloapisComV1Alpha1ServiceEntitlementStatusResponses,
  ReadServicesMiloapisComV1Alpha1ServiceErrors,
  ReadServicesMiloapisComV1Alpha1ServiceResponses,
  ReadServicesMiloapisComV1Alpha1ServiceStatusData,
  ReadServicesMiloapisComV1Alpha1ServiceStatusErrors,
  ReadServicesMiloapisComV1Alpha1ServiceStatusResponses,
  ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationData,
  ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
  ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
  ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationStatusData,
  ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationStatusErrors,
  ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationStatusResponses,
  ReplaceServicesMiloapisComV1Alpha1ServiceConsumerData,
  ReplaceServicesMiloapisComV1Alpha1ServiceConsumerErrors,
  ReplaceServicesMiloapisComV1Alpha1ServiceConsumerResponses,
  ReplaceServicesMiloapisComV1Alpha1ServiceConsumerStatusData,
  ReplaceServicesMiloapisComV1Alpha1ServiceConsumerStatusErrors,
  ReplaceServicesMiloapisComV1Alpha1ServiceConsumerStatusResponses,
  ReplaceServicesMiloapisComV1Alpha1ServiceData,
  ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementData,
  ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
  ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
  ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementStatusData,
  ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementStatusErrors,
  ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementStatusResponses,
  ReplaceServicesMiloapisComV1Alpha1ServiceErrors,
  ReplaceServicesMiloapisComV1Alpha1ServiceResponses,
  ReplaceServicesMiloapisComV1Alpha1ServiceStatusData,
  ReplaceServicesMiloapisComV1Alpha1ServiceStatusErrors,
  ReplaceServicesMiloapisComV1Alpha1ServiceStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * delete collection of ServiceConfiguration
 */
export const deleteServicesMiloapisComV1Alpha1CollectionServiceConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    DeleteServicesMiloapisComV1Alpha1CollectionServiceConfigurationData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).delete<
    DeleteServicesMiloapisComV1Alpha1CollectionServiceConfigurationResponses,
    DeleteServicesMiloapisComV1Alpha1CollectionServiceConfigurationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations',
    ...options,
  });

/**
 * list objects of kind ServiceConfiguration
 */
export const listServicesMiloapisComV1Alpha1ServiceConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListServicesMiloapisComV1Alpha1ServiceConfigurationData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
    ListServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations',
    ...options,
  });

/**
 * create a ServiceConfiguration
 */
export const createServicesMiloapisComV1Alpha1ServiceConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateServicesMiloapisComV1Alpha1ServiceConfigurationData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
    CreateServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a ServiceConfiguration
 */
export const deleteServicesMiloapisComV1Alpha1ServiceConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteServicesMiloapisComV1Alpha1ServiceConfigurationData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
    DeleteServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified ServiceConfiguration
 */
export const readServicesMiloapisComV1Alpha1ServiceConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadServicesMiloapisComV1Alpha1ServiceConfigurationData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
    ReadServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations/{name}',
    ...options,
  });

/**
 * partially update the specified ServiceConfiguration
 */
export const patchServicesMiloapisComV1Alpha1ServiceConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchServicesMiloapisComV1Alpha1ServiceConfigurationData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
    PatchServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified ServiceConfiguration
 */
export const replaceServicesMiloapisComV1Alpha1ServiceConfiguration = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationResponses,
    ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified ServiceConfiguration
 */
export const readServicesMiloapisComV1Alpha1ServiceConfigurationStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadServicesMiloapisComV1Alpha1ServiceConfigurationStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadServicesMiloapisComV1Alpha1ServiceConfigurationStatusResponses,
    ReadServicesMiloapisComV1Alpha1ServiceConfigurationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified ServiceConfiguration
 */
export const patchServicesMiloapisComV1Alpha1ServiceConfigurationStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchServicesMiloapisComV1Alpha1ServiceConfigurationStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchServicesMiloapisComV1Alpha1ServiceConfigurationStatusResponses,
    PatchServicesMiloapisComV1Alpha1ServiceConfigurationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified ServiceConfiguration
 */
export const replaceServicesMiloapisComV1Alpha1ServiceConfigurationStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationStatusResponses,
    ReplaceServicesMiloapisComV1Alpha1ServiceConfigurationStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconfigurations/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of ServiceConsumer
 */
export const deleteServicesMiloapisComV1Alpha1CollectionServiceConsumer = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<DeleteServicesMiloapisComV1Alpha1CollectionServiceConsumerData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteServicesMiloapisComV1Alpha1CollectionServiceConsumerResponses,
    DeleteServicesMiloapisComV1Alpha1CollectionServiceConsumerErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers',
    ...options,
  });

/**
 * list objects of kind ServiceConsumer
 */
export const listServicesMiloapisComV1Alpha1ServiceConsumer = <ThrowOnError extends boolean = true>(
  options?: Options<ListServicesMiloapisComV1Alpha1ServiceConsumerData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListServicesMiloapisComV1Alpha1ServiceConsumerResponses,
    ListServicesMiloapisComV1Alpha1ServiceConsumerErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers',
    ...options,
  });

/**
 * create a ServiceConsumer
 */
export const createServicesMiloapisComV1Alpha1ServiceConsumer = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateServicesMiloapisComV1Alpha1ServiceConsumerData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateServicesMiloapisComV1Alpha1ServiceConsumerResponses,
    CreateServicesMiloapisComV1Alpha1ServiceConsumerErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a ServiceConsumer
 */
export const deleteServicesMiloapisComV1Alpha1ServiceConsumer = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteServicesMiloapisComV1Alpha1ServiceConsumerData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteServicesMiloapisComV1Alpha1ServiceConsumerResponses,
    DeleteServicesMiloapisComV1Alpha1ServiceConsumerErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified ServiceConsumer
 */
export const readServicesMiloapisComV1Alpha1ServiceConsumer = <ThrowOnError extends boolean = true>(
  options: Options<ReadServicesMiloapisComV1Alpha1ServiceConsumerData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadServicesMiloapisComV1Alpha1ServiceConsumerResponses,
    ReadServicesMiloapisComV1Alpha1ServiceConsumerErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers/{name}',
    ...options,
  });

/**
 * partially update the specified ServiceConsumer
 */
export const patchServicesMiloapisComV1Alpha1ServiceConsumer = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchServicesMiloapisComV1Alpha1ServiceConsumerData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchServicesMiloapisComV1Alpha1ServiceConsumerResponses,
    PatchServicesMiloapisComV1Alpha1ServiceConsumerErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified ServiceConsumer
 */
export const replaceServicesMiloapisComV1Alpha1ServiceConsumer = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceServicesMiloapisComV1Alpha1ServiceConsumerData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceServicesMiloapisComV1Alpha1ServiceConsumerResponses,
    ReplaceServicesMiloapisComV1Alpha1ServiceConsumerErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified ServiceConsumer
 */
export const readServicesMiloapisComV1Alpha1ServiceConsumerStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadServicesMiloapisComV1Alpha1ServiceConsumerStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadServicesMiloapisComV1Alpha1ServiceConsumerStatusResponses,
    ReadServicesMiloapisComV1Alpha1ServiceConsumerStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified ServiceConsumer
 */
export const patchServicesMiloapisComV1Alpha1ServiceConsumerStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchServicesMiloapisComV1Alpha1ServiceConsumerStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchServicesMiloapisComV1Alpha1ServiceConsumerStatusResponses,
    PatchServicesMiloapisComV1Alpha1ServiceConsumerStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified ServiceConsumer
 */
export const replaceServicesMiloapisComV1Alpha1ServiceConsumerStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceServicesMiloapisComV1Alpha1ServiceConsumerStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceServicesMiloapisComV1Alpha1ServiceConsumerStatusResponses,
    ReplaceServicesMiloapisComV1Alpha1ServiceConsumerStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceconsumers/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of ServiceEntitlement
 */
export const deleteServicesMiloapisComV1Alpha1CollectionServiceEntitlement = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<DeleteServicesMiloapisComV1Alpha1CollectionServiceEntitlementData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteServicesMiloapisComV1Alpha1CollectionServiceEntitlementResponses,
    DeleteServicesMiloapisComV1Alpha1CollectionServiceEntitlementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements',
    ...options,
  });

/**
 * list objects of kind ServiceEntitlement
 */
export const listServicesMiloapisComV1Alpha1ServiceEntitlement = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListServicesMiloapisComV1Alpha1ServiceEntitlementData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
    ListServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements',
    ...options,
  });

/**
 * create a ServiceEntitlement
 */
export const createServicesMiloapisComV1Alpha1ServiceEntitlement = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateServicesMiloapisComV1Alpha1ServiceEntitlementData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
    CreateServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a ServiceEntitlement
 */
export const deleteServicesMiloapisComV1Alpha1ServiceEntitlement = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteServicesMiloapisComV1Alpha1ServiceEntitlementData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
    DeleteServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified ServiceEntitlement
 */
export const readServicesMiloapisComV1Alpha1ServiceEntitlement = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadServicesMiloapisComV1Alpha1ServiceEntitlementData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
    ReadServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements/{name}',
    ...options,
  });

/**
 * partially update the specified ServiceEntitlement
 */
export const patchServicesMiloapisComV1Alpha1ServiceEntitlement = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchServicesMiloapisComV1Alpha1ServiceEntitlementData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
    PatchServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified ServiceEntitlement
 */
export const replaceServicesMiloapisComV1Alpha1ServiceEntitlement = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementResponses,
    ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified ServiceEntitlement
 */
export const readServicesMiloapisComV1Alpha1ServiceEntitlementStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadServicesMiloapisComV1Alpha1ServiceEntitlementStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadServicesMiloapisComV1Alpha1ServiceEntitlementStatusResponses,
    ReadServicesMiloapisComV1Alpha1ServiceEntitlementStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified ServiceEntitlement
 */
export const patchServicesMiloapisComV1Alpha1ServiceEntitlementStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchServicesMiloapisComV1Alpha1ServiceEntitlementStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchServicesMiloapisComV1Alpha1ServiceEntitlementStatusResponses,
    PatchServicesMiloapisComV1Alpha1ServiceEntitlementStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified ServiceEntitlement
 */
export const replaceServicesMiloapisComV1Alpha1ServiceEntitlementStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementStatusResponses,
    ReplaceServicesMiloapisComV1Alpha1ServiceEntitlementStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/serviceentitlements/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Service
 */
export const deleteServicesMiloapisComV1Alpha1CollectionService = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<DeleteServicesMiloapisComV1Alpha1CollectionServiceData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteServicesMiloapisComV1Alpha1CollectionServiceResponses,
    DeleteServicesMiloapisComV1Alpha1CollectionServiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services',
    ...options,
  });

/**
 * list objects of kind Service
 */
export const listServicesMiloapisComV1Alpha1Service = <ThrowOnError extends boolean = true>(
  options?: Options<ListServicesMiloapisComV1Alpha1ServiceData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListServicesMiloapisComV1Alpha1ServiceResponses,
    ListServicesMiloapisComV1Alpha1ServiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services',
    ...options,
  });

/**
 * create a Service
 */
export const createServicesMiloapisComV1Alpha1Service = <ThrowOnError extends boolean = true>(
  options: Options<CreateServicesMiloapisComV1Alpha1ServiceData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateServicesMiloapisComV1Alpha1ServiceResponses,
    CreateServicesMiloapisComV1Alpha1ServiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a Service
 */
export const deleteServicesMiloapisComV1Alpha1Service = <ThrowOnError extends boolean = true>(
  options: Options<DeleteServicesMiloapisComV1Alpha1ServiceData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteServicesMiloapisComV1Alpha1ServiceResponses,
    DeleteServicesMiloapisComV1Alpha1ServiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Service
 */
export const readServicesMiloapisComV1Alpha1Service = <ThrowOnError extends boolean = true>(
  options: Options<ReadServicesMiloapisComV1Alpha1ServiceData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadServicesMiloapisComV1Alpha1ServiceResponses,
    ReadServicesMiloapisComV1Alpha1ServiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services/{name}',
    ...options,
  });

/**
 * partially update the specified Service
 */
export const patchServicesMiloapisComV1Alpha1Service = <ThrowOnError extends boolean = true>(
  options: Options<PatchServicesMiloapisComV1Alpha1ServiceData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchServicesMiloapisComV1Alpha1ServiceResponses,
    PatchServicesMiloapisComV1Alpha1ServiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Service
 */
export const replaceServicesMiloapisComV1Alpha1Service = <ThrowOnError extends boolean = true>(
  options: Options<ReplaceServicesMiloapisComV1Alpha1ServiceData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceServicesMiloapisComV1Alpha1ServiceResponses,
    ReplaceServicesMiloapisComV1Alpha1ServiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Service
 */
export const readServicesMiloapisComV1Alpha1ServiceStatus = <ThrowOnError extends boolean = true>(
  options: Options<ReadServicesMiloapisComV1Alpha1ServiceStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadServicesMiloapisComV1Alpha1ServiceStatusResponses,
    ReadServicesMiloapisComV1Alpha1ServiceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Service
 */
export const patchServicesMiloapisComV1Alpha1ServiceStatus = <ThrowOnError extends boolean = true>(
  options: Options<PatchServicesMiloapisComV1Alpha1ServiceStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchServicesMiloapisComV1Alpha1ServiceStatusResponses,
    PatchServicesMiloapisComV1Alpha1ServiceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Service
 */
export const replaceServicesMiloapisComV1Alpha1ServiceStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceServicesMiloapisComV1Alpha1ServiceStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceServicesMiloapisComV1Alpha1ServiceStatusResponses,
    ReplaceServicesMiloapisComV1Alpha1ServiceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/services.miloapis.com/v1alpha1/services/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
