// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from '../../shared/client';
import { client } from '../../shared/client.gen';
import type {
  CreateBillingMiloapisComV1Alpha1MeterDefinitionData,
  CreateBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  CreateBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionData,
  DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeData,
  DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingData,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountData,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountResponses,
  DeleteBillingMiloapisComV1Alpha1MeterDefinitionData,
  DeleteBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  DeleteBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesData,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesErrors,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesData,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesErrors,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1MeterDefinitionData,
  ListBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ListBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  ListBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  ListBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ListBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionData,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusData,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionData,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusData,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionData,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusData,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * list objects of kind BillingAccountBinding
 */
export const listBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesResponses,
    ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/billingaccountbindings',
    ...options,
  });

/**
 * list objects of kind BillingAccount
 */
export const listBillingMiloapisComV1Alpha1BillingAccountForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesResponses,
    ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/billingaccounts',
    ...options,
  });

/**
 * delete collection of MeterDefinition
 */
export const deleteBillingMiloapisComV1Alpha1CollectionMeterDefinition = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionData, ThrowOnError>
) =>
  (options?.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions',
    ...options,
  });

/**
 * list objects of kind MeterDefinition
 */
export const listBillingMiloapisComV1Alpha1MeterDefinition = <ThrowOnError extends boolean = true>(
  options?: Options<ListBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    ListBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions',
    ...options,
  });

/**
 * create a MeterDefinition
 */
export const createBillingMiloapisComV1Alpha1MeterDefinition = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    CreateBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a MeterDefinition
 */
export const deleteBillingMiloapisComV1Alpha1MeterDefinition = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    DeleteBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified MeterDefinition
 */
export const readBillingMiloapisComV1Alpha1MeterDefinition = <ThrowOnError extends boolean = true>(
  options: Options<ReadBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    ReadBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}',
    ...options,
  });

/**
 * partially update the specified MeterDefinition
 */
export const patchBillingMiloapisComV1Alpha1MeterDefinition = <ThrowOnError extends boolean = true>(
  options: Options<PatchBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    PatchBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified MeterDefinition
 */
export const replaceBillingMiloapisComV1Alpha1MeterDefinition = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    ReplaceBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified MeterDefinition
 */
export const readBillingMiloapisComV1Alpha1MeterDefinitionStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
    ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified MeterDefinition
 */
export const patchBillingMiloapisComV1Alpha1MeterDefinitionStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
    PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified MeterDefinition
 */
export const replaceBillingMiloapisComV1Alpha1MeterDefinitionStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of MonitoredResourceType
 */
export const deleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeData,
    ThrowOnError
  >
) =>
  (options?.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes',
    ...options,
  });

/**
 * list objects of kind MonitoredResourceType
 */
export const listBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    ListBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes',
    ...options,
  });

/**
 * create a MonitoredResourceType
 */
export const createBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a MonitoredResourceType
 */
export const deleteBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified MonitoredResourceType
 */
export const readBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}',
    ...options,
  });

/**
 * partially update the specified MonitoredResourceType
 */
export const patchBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified MonitoredResourceType
 */
export const replaceBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified MonitoredResourceType
 */
export const readBillingMiloapisComV1Alpha1MonitoredResourceTypeStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
    ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified MonitoredResourceType
 */
export const patchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
    PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified MonitoredResourceType
 */
export const replaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of BillingAccountBinding
 */
export const deleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings',
    ...options,
  });

/**
 * list objects of kind BillingAccountBinding
 */
export const listBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings',
    ...options,
  });

/**
 * create a BillingAccountBinding
 */
export const createBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
    ThrowOnError
  >
) =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a BillingAccountBinding
 */
export const deleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified BillingAccountBinding
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
  });

/**
 * partially update the specified BillingAccountBinding
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified BillingAccountBinding
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified BillingAccountBinding
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified BillingAccountBinding
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified BillingAccountBinding
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of BillingAccount
 */
export const deleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountData,
    ThrowOnError
  >
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts',
    ...options,
  });

/**
 * list objects of kind BillingAccount
 */
export const listBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ListBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts',
    ...options,
  });

/**
 * create a BillingAccount
 */
export const createBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a BillingAccount
 */
export const deleteBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified BillingAccount
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
  });

/**
 * partially update the specified BillingAccount
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified BillingAccount
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified BillingAccount
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccountStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified BillingAccount
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified BillingAccount
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
    ThrowOnError
  >
) =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
