// This file is auto-generated by @hey-api/openapi-ts
import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from '../../shared/client';
import { client } from '../../shared/client.gen';
import type {
  CreateBillingMiloapisComV1Alpha1MeterDefinitionData,
  CreateBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  CreateBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedInvoiceData,
  CreateBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  CreateBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedPaymentMethodData,
  CreateBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  CreateBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  CreateBillingMiloapisComV1Alpha1PaymentMethodClassData,
  CreateBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  CreateBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionData,
  DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeData,
  DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingData,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountData,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedInvoiceData,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedInvoiceErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedInvoiceResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedPaymentMethodData,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedPaymentMethodErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedPaymentMethodResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionPaymentMethodClassData,
  DeleteBillingMiloapisComV1Alpha1CollectionPaymentMethodClassErrors,
  DeleteBillingMiloapisComV1Alpha1CollectionPaymentMethodClassResponses,
  DeleteBillingMiloapisComV1Alpha1MeterDefinitionData,
  DeleteBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  DeleteBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedInvoiceData,
  DeleteBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  DeleteBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedPaymentMethodData,
  DeleteBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  DeleteBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  DeleteBillingMiloapisComV1Alpha1PaymentMethodClassData,
  DeleteBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  DeleteBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesData,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesErrors,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesData,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesErrors,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1InvoiceForAllNamespacesData,
  ListBillingMiloapisComV1Alpha1InvoiceForAllNamespacesErrors,
  ListBillingMiloapisComV1Alpha1InvoiceForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1MeterDefinitionData,
  ListBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ListBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  ListBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  ListBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ListBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ListBillingMiloapisComV1Alpha1NamespacedInvoiceData,
  ListBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  ListBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  ListBillingMiloapisComV1Alpha1NamespacedPaymentMethodData,
  ListBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  ListBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  ListBillingMiloapisComV1Alpha1PaymentMethodClassData,
  ListBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  ListBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  ListBillingMiloapisComV1Alpha1PaymentMethodForAllNamespacesData,
  ListBillingMiloapisComV1Alpha1PaymentMethodForAllNamespacesErrors,
  ListBillingMiloapisComV1Alpha1PaymentMethodForAllNamespacesResponses,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionData,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusData,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceData,
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceStatusData,
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceStatusErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodData,
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusData,
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusErrors,
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusResponses,
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassData,
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassStatusData,
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassStatusErrors,
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassStatusResponses,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionData,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusData,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceData,
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceStatusData,
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceStatusErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodData,
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusData,
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusErrors,
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusResponses,
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassData,
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassStatusData,
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassStatusErrors,
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionData,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusData,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeData,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceStatusData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusData,
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassData,
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassStatusData,
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassStatusErrors,
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassStatusResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * list objects of kind BillingAccountBinding
 */
export const listBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesData,
    ThrowOnError
  >
): RequestResult<
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesResponses,
    ListBillingMiloapisComV1Alpha1BillingAccountBindingForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/billingaccountbindings',
    ...options,
  });

/**
 * list objects of kind BillingAccount
 */
export const listBillingMiloapisComV1Alpha1BillingAccountForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesResponses,
    ListBillingMiloapisComV1Alpha1BillingAccountForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/billingaccounts',
    ...options,
  });

/**
 * list objects of kind Invoice
 */
export const listBillingMiloapisComV1Alpha1InvoiceForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListBillingMiloapisComV1Alpha1InvoiceForAllNamespacesData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1InvoiceForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1InvoiceForAllNamespacesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1InvoiceForAllNamespacesResponses,
    ListBillingMiloapisComV1Alpha1InvoiceForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/invoices',
    ...options,
  });

/**
 * delete collection of MeterDefinition
 */
export const deleteBillingMiloapisComV1Alpha1CollectionMeterDefinition = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionData, ThrowOnError>
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionMeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions',
    ...options,
  });

/**
 * list objects of kind MeterDefinition
 */
export const listBillingMiloapisComV1Alpha1MeterDefinition = <ThrowOnError extends boolean = true>(
  options?: Options<ListBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  ListBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    ListBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions',
    ...options,
  });

/**
 * create a MeterDefinition
 */
export const createBillingMiloapisComV1Alpha1MeterDefinition = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
): RequestResult<
  CreateBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  CreateBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    CreateBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a MeterDefinition
 */
export const deleteBillingMiloapisComV1Alpha1MeterDefinition = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  DeleteBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    DeleteBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified MeterDefinition
 */
export const readBillingMiloapisComV1Alpha1MeterDefinition = <ThrowOnError extends boolean = true>(
  options: Options<ReadBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    ReadBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}',
    ...options,
  });

/**
 * partially update the specified MeterDefinition
 */
export const patchBillingMiloapisComV1Alpha1MeterDefinition = <ThrowOnError extends boolean = true>(
  options: Options<PatchBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    PatchBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified MeterDefinition
 */
export const replaceBillingMiloapisComV1Alpha1MeterDefinition = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1MeterDefinitionData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionResponses,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1MeterDefinitionResponses,
    ReplaceBillingMiloapisComV1Alpha1MeterDefinitionErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified MeterDefinition
 */
export const readBillingMiloapisComV1Alpha1MeterDefinitionStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
  ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
    ReadBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified MeterDefinition
 */
export const patchBillingMiloapisComV1Alpha1MeterDefinitionStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
  PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
    PatchBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified MeterDefinition
 */
export const replaceBillingMiloapisComV1Alpha1MeterDefinitionStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1MeterDefinitionStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/meterdefinitions/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of MonitoredResourceType
 */
export const deleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<
    DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeData,
    ThrowOnError
  >
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionMonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes',
    ...options,
  });

/**
 * list objects of kind MonitoredResourceType
 */
export const listBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  ListBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    ListBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes',
    ...options,
  });

/**
 * create a MonitoredResourceType
 */
export const createBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
): RequestResult<
  CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    CreateBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a MonitoredResourceType
 */
export const deleteBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    DeleteBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified MonitoredResourceType
 */
export const readBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}',
    ...options,
  });

/**
 * partially update the specified MonitoredResourceType
 */
export const patchBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified MonitoredResourceType
 */
export const replaceBillingMiloapisComV1Alpha1MonitoredResourceType = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeResponses,
    ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified MonitoredResourceType
 */
export const readBillingMiloapisComV1Alpha1MonitoredResourceTypeStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
  ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
    ReadBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified MonitoredResourceType
 */
export const patchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
  PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
    PatchBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified MonitoredResourceType
 */
export const replaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1MonitoredResourceTypeStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/monitoredresourcetypes/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of BillingAccountBinding
 */
export const deleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingData,
    ThrowOnError
  >
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings',
    ...options,
  });

/**
 * list objects of kind BillingAccountBinding
 */
export const listBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings',
    ...options,
  });

/**
 * create a BillingAccountBinding
 */
export const createBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
    ThrowOnError
  >
): RequestResult<
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a BillingAccountBinding
 */
export const deleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
    ThrowOnError
  >
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified BillingAccountBinding
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
  });

/**
 * partially update the specified BillingAccountBinding
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified BillingAccountBinding
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBinding = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingData,
    ThrowOnError
  >
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified BillingAccountBinding
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
    ThrowOnError
  >
): RequestResult<
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified BillingAccountBinding
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
    ThrowOnError
  >
): RequestResult<
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified BillingAccountBinding
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusData,
    ThrowOnError
  >
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountBindingStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccountbindings/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of BillingAccount
 */
export const deleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountData,
    ThrowOnError
  >
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts',
    ...options,
  });

/**
 * list objects of kind BillingAccount
 */
export const listBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ListBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ListBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    ListBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts',
    ...options,
  });

/**
 * create a BillingAccount
 */
export const createBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
): RequestResult<
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    CreateBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a BillingAccount
 */
export const deleteBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    DeleteBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified BillingAccount
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
  });

/**
 * partially update the specified BillingAccount
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified BillingAccount
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccount = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified BillingAccount
 */
export const readBillingMiloapisComV1Alpha1NamespacedBillingAccountStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified BillingAccount
 */
export const patchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified BillingAccount
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusData,
    ThrowOnError
  >
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedBillingAccountStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/billingaccounts/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of Invoice
 */
export const deleteBillingMiloapisComV1Alpha1CollectionNamespacedInvoice = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1CollectionNamespacedInvoiceData, ThrowOnError>
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedInvoiceResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedInvoiceErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedInvoiceResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedInvoiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices',
    ...options,
  });

/**
 * list objects of kind Invoice
 */
export const listBillingMiloapisComV1Alpha1NamespacedInvoice = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ListBillingMiloapisComV1Alpha1NamespacedInvoiceData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  ListBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
    ListBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices',
    ...options,
  });

/**
 * create an Invoice
 */
export const createBillingMiloapisComV1Alpha1NamespacedInvoice = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1NamespacedInvoiceData, ThrowOnError>
): RequestResult<
  CreateBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
    CreateBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete an Invoice
 */
export const deleteBillingMiloapisComV1Alpha1NamespacedInvoice = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1NamespacedInvoiceData, ThrowOnError>
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
    DeleteBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified Invoice
 */
export const readBillingMiloapisComV1Alpha1NamespacedInvoice = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedInvoiceData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices/{name}',
    ...options,
  });

/**
 * partially update the specified Invoice
 */
export const patchBillingMiloapisComV1Alpha1NamespacedInvoice = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedInvoiceData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified Invoice
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedInvoice = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified Invoice
 */
export const readBillingMiloapisComV1Alpha1NamespacedInvoiceStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedInvoiceStatusData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedInvoiceStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedInvoiceStatusResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedInvoiceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified Invoice
 */
export const patchBillingMiloapisComV1Alpha1NamespacedInvoiceStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedInvoiceStatusData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedInvoiceStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedInvoiceStatusResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedInvoiceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified Invoice
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedInvoiceStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceStatusData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedInvoiceStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/invoices/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of PaymentMethod
 */
export const deleteBillingMiloapisComV1Alpha1CollectionNamespacedPaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedPaymentMethodData,
    ThrowOnError
  >
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedPaymentMethodResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionNamespacedPaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedPaymentMethodResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionNamespacedPaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods',
    ...options,
  });

/**
 * list objects of kind PaymentMethod
 */
export const listBillingMiloapisComV1Alpha1NamespacedPaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ListBillingMiloapisComV1Alpha1NamespacedPaymentMethodData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  ListBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ListBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
    ListBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods',
    ...options,
  });

/**
 * create a PaymentMethod
 */
export const createBillingMiloapisComV1Alpha1NamespacedPaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1NamespacedPaymentMethodData, ThrowOnError>
): RequestResult<
  CreateBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  CreateBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
    CreateBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a PaymentMethod
 */
export const deleteBillingMiloapisComV1Alpha1NamespacedPaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1NamespacedPaymentMethodData, ThrowOnError>
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  DeleteBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
    DeleteBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified PaymentMethod
 */
export const readBillingMiloapisComV1Alpha1NamespacedPaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods/{name}',
    ...options,
  });

/**
 * partially update the specified PaymentMethod
 */
export const patchBillingMiloapisComV1Alpha1NamespacedPaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified PaymentMethod
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedPaymentMethod = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified PaymentMethod
 */
export const readBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusResponses,
  ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusResponses,
    ReadBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified PaymentMethod
 */
export const patchBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusResponses,
  PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusResponses,
    PatchBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified PaymentMethod
 */
export const replaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1NamespacedPaymentMethodStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/namespaces/{namespace}/paymentmethods/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete collection of PaymentMethodClass
 */
export const deleteBillingMiloapisComV1Alpha1CollectionPaymentMethodClass = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<DeleteBillingMiloapisComV1Alpha1CollectionPaymentMethodClassData, ThrowOnError>
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1CollectionPaymentMethodClassResponses,
  DeleteBillingMiloapisComV1Alpha1CollectionPaymentMethodClassErrors,
  ThrowOnError
> =>
  (options?.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1CollectionPaymentMethodClassResponses,
    DeleteBillingMiloapisComV1Alpha1CollectionPaymentMethodClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses',
    ...options,
  });

/**
 * list objects of kind PaymentMethodClass
 */
export const listBillingMiloapisComV1Alpha1PaymentMethodClass = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListBillingMiloapisComV1Alpha1PaymentMethodClassData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  ListBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
    ListBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses',
    ...options,
  });

/**
 * create a PaymentMethodClass
 */
export const createBillingMiloapisComV1Alpha1PaymentMethodClass = <
  ThrowOnError extends boolean = true,
>(
  options: Options<CreateBillingMiloapisComV1Alpha1PaymentMethodClassData, ThrowOnError>
): RequestResult<
  CreateBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  CreateBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
    CreateBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * delete a PaymentMethodClass
 */
export const deleteBillingMiloapisComV1Alpha1PaymentMethodClass = <
  ThrowOnError extends boolean = true,
>(
  options: Options<DeleteBillingMiloapisComV1Alpha1PaymentMethodClassData, ThrowOnError>
): RequestResult<
  DeleteBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  DeleteBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
    DeleteBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read the specified PaymentMethodClass
 */
export const readBillingMiloapisComV1Alpha1PaymentMethodClass = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1PaymentMethodClassData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
    ReadBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses/{name}',
    ...options,
  });

/**
 * partially update the specified PaymentMethodClass
 */
export const patchBillingMiloapisComV1Alpha1PaymentMethodClass = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1PaymentMethodClassData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
    PatchBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace the specified PaymentMethodClass
 */
export const replaceBillingMiloapisComV1Alpha1PaymentMethodClass = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassResponses,
    ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses/{name}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * read status of the specified PaymentMethodClass
 */
export const readBillingMiloapisComV1Alpha1PaymentMethodClassStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReadBillingMiloapisComV1Alpha1PaymentMethodClassStatusData, ThrowOnError>
): RequestResult<
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassStatusResponses,
  ReadBillingMiloapisComV1Alpha1PaymentMethodClassStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ReadBillingMiloapisComV1Alpha1PaymentMethodClassStatusResponses,
    ReadBillingMiloapisComV1Alpha1PaymentMethodClassStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses/{name}/status',
    ...options,
  });

/**
 * partially update status of the specified PaymentMethodClass
 */
export const patchBillingMiloapisComV1Alpha1PaymentMethodClassStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<PatchBillingMiloapisComV1Alpha1PaymentMethodClassStatusData, ThrowOnError>
): RequestResult<
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassStatusResponses,
  PatchBillingMiloapisComV1Alpha1PaymentMethodClassStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).patch<
    PatchBillingMiloapisComV1Alpha1PaymentMethodClassStatusResponses,
    PatchBillingMiloapisComV1Alpha1PaymentMethodClassStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json-patch+json',
      ...options.headers,
    },
  });

/**
 * replace status of the specified PaymentMethodClass
 */
export const replaceBillingMiloapisComV1Alpha1PaymentMethodClassStatus = <
  ThrowOnError extends boolean = true,
>(
  options: Options<ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassStatusData, ThrowOnError>
): RequestResult<
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassStatusResponses,
  ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassStatusErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassStatusResponses,
    ReplaceBillingMiloapisComV1Alpha1PaymentMethodClassStatusErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethodclasses/{name}/status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * list objects of kind PaymentMethod
 */
export const listBillingMiloapisComV1Alpha1PaymentMethodForAllNamespaces = <
  ThrowOnError extends boolean = true,
>(
  options?: Options<ListBillingMiloapisComV1Alpha1PaymentMethodForAllNamespacesData, ThrowOnError>
): RequestResult<
  ListBillingMiloapisComV1Alpha1PaymentMethodForAllNamespacesResponses,
  ListBillingMiloapisComV1Alpha1PaymentMethodForAllNamespacesErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    ListBillingMiloapisComV1Alpha1PaymentMethodForAllNamespacesResponses,
    ListBillingMiloapisComV1Alpha1PaymentMethodForAllNamespacesErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/apis/billing.miloapis.com/v1alpha1/paymentmethods',
    ...options,
  });
