name: Publish Staff Portal

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'

  release:
    types: ['published']

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  build-and-push:
    permissions:
      contents: read
      packages: write
      id-token: write

    runs-on: ubuntu-latest
    needs: check-files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/datum-cloud/staff-portal
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=ref,event=branch,suffix=-{{commit_date 'YYYYMMDD-HHmmss'}}
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha

      - name: Build Portal
        id: push
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
